# permissions for end users to view deploymentconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymentconfig-viewer-role
rules:
- apiGroups:
  - app.stakater.com
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.stakater.com
  resources:
  - deploymentconfigs/status
  verbs:
  - get
